### ISSUE TITLE
Unable to modify PVR templates

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/overload#68]
When modifying existing template:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python27\lib\lib-tk\Tkinter.py", line 1547, in __call__
    return self.func(*args)
...
  File "C:\Program Files\Python27\lib\lib-tk\Tkinter.py", line 2634, in get
    return self.tk.call(self._w, 'get', first)
TclError: bad listbox index "": must be active, anchor, end, @x,y, or a number

**Comment by klinga** [comment]
fixed
